// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#pragma once

#include <functional>

namespace interaxon { namespace bridge {

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a Battery packet.
 * \sa \enumlink{MuseDataPacketType,BATTERY,IXNMuseDataPacketTypeBattery}
 * \sa \functionlink{MuseDataPacket,getBatteryValue,get_battery_value}
 */
enum class Battery : int {
    /** Charge percentage remaining of battery. */
    CHARGE_PERCENTAGE_REMAINING,
    /** Millivolts of battery from the view of the fuel gauge. */
    MILLIVOLTS,
    /** Temperature in degrees Celsius. */
    TEMPERATURE_CELSIUS,
    /** Average current in microamps. */
    AVERAGE_CURRENT,
    /** Remaining seconds until charge depleted (while discharging). */
    TIME_TO_EMPTY,
    /** Remaining seconds until fully charged (while charging). */
    TIME_TO_FULL,
    /** Full capacity of battery in mAh.   */
    BATTERY_CAPACITY,
    /** Remaining capacity of battery in mAh. */
    REMAINING_CAPACITY,
    /** Percentage battery age calculated from capacity. */
    BATTERY_AGE,
    /** Total number of charge/discharge cycles. */
    TOTAL_CYCLES,
};

} }  // namespace interaxon::bridge

namespace std {

template <>
struct hash<::interaxon::bridge::Battery> {
    size_t operator()(::interaxon::bridge::Battery type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
