// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#pragma once

#include <functional>

namespace interaxon { namespace bridge {

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Defines all possible Muse presets.
 * <br>
 *
 * Presets are specific to the model of headband.  For example, setting a preset
 * that is intended for a \muse2014 headband on a \muse2016 headband will not work.
 * Attempting to set an incorrect preset on a headband will result
 * in a warning in the log and the incorrect preset will be ignored.  To avoid this, you should
 * first connect to the headband without setting a preset and check the \classlink{MuseConfiguration}
 * to get the model of the headband and then set the appropriate preset.
 * You can also obtain the current preset of the headband from the
 * \classlink{MuseConfiguration}
 * <br>
 *
 * If you change the preset while the headband is connected, the headband will disconnect.
 * If the preset is valid for that headband model, then the headband will automatically reconnect.
 * If the preset is invalid for that headband model, then the headband will remain disconnected.
 *
 * \sa \classlink{MuseConfiguration}
 */
enum class MusePreset : int {
    /**
     * 4 CH EEG, 10 bit @ 220 Hz, compression ON, no accelerometer, no battery
     * data, no error data, no DRL/REF data.
     * <br>
     *
     * Availability: \muse2014 only
     */
    PRESET_10,
    /**
     * 4 CH EEG, 10 bit @ 220 Hz, compression ON, 50 Hz accelerometer data,
     * 0.1 Hz battery data, no error data, no DRL/REF data
     * <br>
     *
     * Availability: \muse2014 only
     */
    PRESET_12,
    /**
     * 4 CH EEG, 10 bit @ 220 Hz, compression ON, 50 Hz accelerometer data,
     * 0.1 Hz battery data, real-time error data, 10 bit @ 10 Hz DRL/REF data
     * <br>
     *
     * This is the default for \muse2014.
     * <br>
     *
     * Availability: \muse2014 only
     */
    PRESET_14,
    /**
     * 5 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF.
     * <br>
     *
     * Availability: \muse2016, \muse2018, \muse2019, \muse2021, \muse2024
     */
    PRESET_20,
    /**
     * 4 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF.
     * <br>
     *
     * This is the default for \muse2016, \muse2018, \muse2019, \muse2021, \muse2024.
     * <br>
     *
     * Availability: \muse2016, \muse2018, \muse2019, \muse2021, \muse2024
     */
    PRESET_21,
    /**
     * 4 CH EEG, 12 bit @ 256 Hz, 0.1 Hz battery,
     * 32 Hz DRL/REF.
     * <br>
     *
     * Availability: \muse2016, \muse2018, \muse2019, \muse2021, \muse2024
     */
    PRESET_22,
    /**
     * 5 CH EEG, 12 bit @ 256 Hz, 0.1 Hz battery,
     * 32 Hz DRL/REF.
     * <br>
     *
     * Availability: \muse2018, \muse2019, \muse2021, \muse2024
     */
    PRESET_23,
    /**
     * 6 CH EEG, 16 bit @ 500 Hz, 50 Hz accelerometer, 0.1 Hz battery,
     * compression OFF, notch filter OFF, no error data, no DRL/REF data
     * <br>
     *
     * Research preset:<br>
     * Only the following data packets are generated with this preset:
     * \enumlink{MuseDataPacketType,EEG,IXNMuseDataPacketTypeEeg},
     * \enumlink{MuseDataPacketType,ACCELEROMETER,IXNMuseDataPacketTypeAccelerometer},
     * \enumlink{MuseDataPacketType,BATTERY,IXNMuseDataPacketTypeBattery}
     * <br>
     * Artifacts are not generated with this preset.<br>
     *
     * Availability: \muse2014 only
     */
    PRESET_AB,
    /**
     * 4 CH EEG, 16 bit @ 500 Hz, 50 Hz accelerometer, 0.1 Hz battery,
     * compression OFF, notch filter OFF, no error data, no DRL/REF data
     * <br>
     *
     * Research preset:<br>
     * Only the following data packets are generated with this preset:
     * \enumlink{MuseDataPacketType,EEG,IXNMuseDataPacketTypeEeg},
     * \enumlink{MuseDataPacketType,ACCELEROMETER,IXNMuseDataPacketTypeAccelerometer},
     * \enumlink{MuseDataPacketType,BATTERY,IXNMuseDataPacketTypeBattery}
     * <br>
     * Artifacts are not generated with this preset.<br>
     *
     * Availability: \muse2014 only
     */
    PRESET_AD,
    /**
     * 4 CH EEG, 12 bit @ 256 Hz, 0.1 Hz battery,
     * 32 Hz DRL/REF, 52 Hz Acc, Gyro and Magnetometer,
     * 0.1 Hz for UV and Pressure.
     * <br>
     *
     * Availability: glasses only
     */
    PRESET_31,
    /**
     * No EEG data, only other sensors.
     * 32 Hz DRL/REF, 52 Hz Acc, Gyro and Magnetometer,
     * 0.1 Hz for battery, UV and Pressure.
     * <br>
     *
     * Availability: glasses only
     */
    PRESET_32,
    /**
     * 5 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF, PPG @ 64 Hz
     * <br>
     *
     * Availability: \muse2018, \muse2019, \muse2021, \muse2024
     */
    PRESET_50,
    /**
     * 4 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF, PPG @ 64 Hz
     * <br>
     *
     * Availability: \muse2018, \muse2019, \muse2021, \muse2024
     */
    PRESET_51,
    /**
     * 4 CH EEG, 12 bit @ 256 Hz, 0.1 Hz battery,
     * 32 Hz DRL/REF, PPG @ 64 Hz
     * <br>
     *
     * Availability: \muse2018, \muse2019, \muse2021, \muse2024
     */
    PRESET_52,
    /**
     * 6 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF, PPG @ 64 Hz
     * <br>
     *
     * Availability: \muse2019, \muse2021, \muse2024
     */
    PRESET_53,
    /**
     * 6 CH EEG, 12 bit @ 128 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 16 Hz DRL/REF
     * <br>
     *
     * Availability: \muse2021
     */
    PRESET_54,
    /**
     * 4 CH EEG, 12 bit @ 128 Hz, 0.1 Hz battery,
     * 16 Hz DRL/REF, PPG @ 64 Hz
     * <br>
     *
     * Availability: \muse2021
     */
    PRESET_55,
    /**
     * 5 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF, PPG @ 64 Hz, THERMISTOR @ 16 Hz
     * <br>
     *
     * Availability: \muse2019, \muse2021
     */
    PRESET_60,
    /**
     * 4 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF, PPG @ 64 Hz, THERMISTOR @ 16 Hz
     * <br>
     *
     * Availability: \muse2019, \muse2021
     */
    PRESET_61,
    /**
     * 6 CH EEG, 12 bit @ 256 Hz, 52 Hz accelerometer/gyro, 0.1 Hz battery,
     * 32 Hz DRL/REF, PPG @ 64 Hz, THERMISTOR @ 16 Hz
     * <br>
     *
     * Availability: \muse2019, \muse2021
     */
    PRESET_63,
    /**
     * 4 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1021,
    /**
     * 8 CH EEG, 14 bit @ 256 Hz, 1 Hz battery,
     * 32 Hz DRL/REF
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1022,
    /**
     * Battery only @ 50 Hz
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1023,
    /**
     * 52 Hz accelerometer/gyro
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1024,
    /**
     * 16 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1025,
    /**
     * 16 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1026,
    /**
     * 8 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1027,
    /**
     * 8 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1028,
    /**
     * 4 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1029,
    /**
     * 4 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_102A,
    /**
     * 4 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 16 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1031,
    /**
     * 4 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 16 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1032,
    /**
     * 4 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 8 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1033,
    /**
     * 4 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 8 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1034,
    /**
     * 4 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 4 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1035,
    /**
     * 4 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 4 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1036,
    /**
     * 8 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 16 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1041,
    /**
     * 8 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 16 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1042,
    /**
     * 8 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 8 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1043,
    /**
     * 8 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 8 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1044,
    /**
     * 8 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 4 CH Optics @ 64 Hz, low power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1045,
    /**
     * 8 CH EEG, 14 bit @ 256 Hz, 52 Hz accelerometer/gyro, 1 Hz battery,
     * 32 Hz DRL/REF, 4 CH Optics @ 64 Hz, high power
     * <br>
     * 
     * Availability: \muse2025
     */
    PRESET_1046,
};

} }  // namespace interaxon::bridge

namespace std {

template <>
struct hash<::interaxon::bridge::MusePreset> {
    size_t operator()(::interaxon::bridge::MusePreset type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
